version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik-proxy
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    networks:
      - proxy
    ports:
      - "80:80" # http
      - "443:443" # https
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/traefik.yml:ro"
      - "./config/acme.json:/acme.json"
      - "./config:/config"
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # Proxy
      - traefik.http.routers.traefik-ui.entrypoints=websecure
      - traefik.http.routers.traefik-ui.rule=Host(`${TRAEFIK_URL}`)
      - traefik.http.routers.traefik-ui.service=api@internal
      - traefik.http.routers.traefik-ui.middlewares=user-auth@file

  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: traefik-portainer
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    networks:
      - proxy
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./storage/portainer-data:/data"
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # Proxy
      - traefik.http.routers.portainer-secure.entrypoints=websecure
      - traefik.http.routers.portainer-secure.rule=Host(`${PORTAINER_URL}`)
      - traefik.http.routers.portainer-secure.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000

volumes:
  storage:


networks:
  proxy:
    external: true
